# Generated by Django 3.2.9 on 2022-06-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Account_No_Bank',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Directors_Partners',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Funding_requirements',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Funding_status',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Name_of_bank',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='PAN',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Registered_address',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Socia_media_links',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Website',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='founders_email',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_of_legal_entity',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_incorporation',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
    ]
