# Generated by Django 3.2.9 on 2022-06-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220625_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info_filled',
            field=models.BooleanField(default=False),
        ),
    ]
