# Generated by Django 3.2.9 on 2022-06-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220625_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Account_No_Bank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Funding_requirements',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name_of_bank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='PAN',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
