# Generated by Django 3.2.9 on 2022-06-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220625_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Name_of_bank',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
